### PR TITLE
fix the path of the configured `glfw3Config[Version].cmake` files

### PR DESCRIPTION
**Pull request by tamaskenez**
The installation of the `glfw3Config.cmake` and `glfw3ConfigVersion.cmake` files failed because incorrect destination paths were given to `configure_package_config_file` and `write_basic_package_version_file`.

I fixed it in accordance with [the CMake docs](http://www.cmake.org/cmake/help/v3.2/module/CMakePackageConfigHelpers.html). Please review and apply if agreed.

Note: the `hide` subdir is to prevent `find_package` to accidentaly find the config-module in the build-tree (a deprecated Windows-only feature).

### CODE REVIEW

**Comment by shaxbee** [comment]
@tamaskenez Thanks for patch but it is not necessary to provide CMAKE_CURRENT_BINARY_DIR there as both command output parameters default to prefixing it anyway.

The reason why GLFW_INSTALL_CONFIG_DIR is being used there is because we have separate build and install tree package config files.

```
<output>
Path to the output file or directory. 
A relative path is treated with respect to the value of CMAKE_CURRENT_BINARY_DIR. 
If the path names an existing directory the output file is placed in that directory 
with the same file name as the input file.
```

**Comment by tamaskenez** [comment]
You're right about default paths. But still, your master fails to build on my system with this error:

```
-- Install configuration: "Release"
-- Installing: C:/ki/grs/mapbox-gl-native-cake/out/include/GLFW
-- Installing: C:/ki/grs/mapbox-gl-native-cake/out/include/GLFW/glfw3.h
-- Installing: C:/ki/grs/mapbox-gl-native-cake/out/include/GLFW/glfw3native.h
CMake Error at cmake_install.cmake:35 (file):
  file INSTALL cannot find
  "C:/ki/grs/mapbox-gl-native-cake/glfw/lib/cmake/glfw3/glfw3Config.cmake".
```

My system is win8/Cmake-3.2.1/msvc-2015rc

So I reverted part of my pull-request and kept only the lines critical for a successful build. What do you think? Should it work without these changes?

**Comment by tamaskenez** [comment]
Please hold on, I need to check how the 'separate build and install tree package config files' thing relates to my commits.

**Comment by shaxbee** [comment]
OK, feel free to add cmake_binary_dir to relevant output paths then...

**Comment by tamaskenez** [comment]
Finaly I've found a solution that fully agrees with your intentions and does not cause any errors.
I'm creating another pull request for that one and closing this.

**Pull request closed without merging**
